# Generated by Django 3.1.2 on 2021-01-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0002_auto_20210126_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='content',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cafe_address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
