# Generated by Django 3.1.3 on 2020-11-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EventHubApp.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default=None, max_length=450),
            preserve_default=False,
        ),
    ]
