# Generated by Django 3.1.2 on 2020-12-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0003_auto_20201223_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rate',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
