# Generated by Django 3.1.2 on 2020-12-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0004_event_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rate_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
