# Generated by Django 3.1.5 on 2021-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0004_auto_20210205_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='content',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
