# Generated by Django 3.1.2 on 2020-12-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0005_event_rate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rate',
            field=models.FloatField(default=None, null=True),
        ),
    ]
