# Generated by Django 3.1.2 on 2020-12-25 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0007_eventcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='like_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventHubApp.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
