# Generated by Django 3.1.2 on 2020-12-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0008_auto_20201225_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='EventComment',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EventHubApp.eventcomment'),
        ),
    ]
