# Generated by Django 3.1.2 on 2020-12-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0009_auto_20201225_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='is_participant',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
