# Generated by Django 3.1.2 on 2020-12-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventHubApp', '0010_eventcomment_is_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
